### ISSUE TITLE
ERROR: http?.setGlobalProxyFromEnv is not a function

### ISSUE THREAD

**Issue by mdPlusPlus** [DmitryScaletta/twitch-dlp#85]
```
$ npx twitch-dlp@latest -o '%(upload_date)s - %(title)s [%(id)s].%(ext)s' --retry-streams 90 --live-from-start https://www.twitch.tv/USERNAME

ERROR: http?.setGlobalProxyFromEnv is not a function

```

Started happening today after update to `twitch-dlp@0.5.29`

It seems to work fine with `twitch-dlp@0.5.28`:

```
$ npx twitch-dlp@0.5.28 -o '%(upload_date)s - %(title)s [%(id)s].%(ext)s' --retry-streams 90 --live-from-start https://www.twitch.tv/USERNAME

Downloading stream metadata
[retry-streams] Waiting for streams. Retry every 90 second(s)
```
